name: drag_anim
description: Support reorderable table drag and drop sorting of all widgets (including slivers)ã€‚ Waterfall, listView, and GridView
version: 1.2.2
homepage: https://github.com/qq1023308356/drag_anim

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=3.10.6"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
