name: drag_anim
description: A drag that supports all components, draggable。Waterfall、listView、GridView、flutter_staggered_grid_view、Wrap、Row、Column  All supported
version: 1.1.3
homepage: https://github.com/qq1023308356/drag_anim

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=3.10.6"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
