name: reorderable_anim
description: Support reorderable for all widgets, sliverã€‚Waterfallã€listViewã€GridView
version: 1.1.6
homepage: https://github.com/qq1023308356/drag_anim

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=3.10.6"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
